import React, { useState } from 'react';
import {
  Copy,
  Mail,
  Download,
  Send,
  CheckCircle2,
  AlertTriangle,
  ArrowLeft,
  Sparkles,
  Building,
  Calendar,
  Clock,
  ShieldCheck,
  FileText
} from 'lucide-react';
import { generateDisputePDF } from '../../utils/pdfGenerator';
import { REGULATORY_AUTHORITIES } from '../../data/providers';

export default function DraftStep({
  complaint,
  setComplaint,
  tone,
  setTone,
  provider,
  dispute,
  onBack,
  onMarkAsSent
}) {
  const [copied, setCopied] = useState(false);
  const [isExportingPDF, setIsExportingPDF] = useState(false);

  const country = provider?.country || (dispute?.transactions?.[0]?.currency === "ZAR" ? "ZA" : "NG");
  const regulator = REGULATORY_AUTHORITIES[country];
  const primaryTx = dispute?.transactions?.[0] || {};

  // Copy Subject & Body to Clipboard
  const handleCopy = () => {
    const fullText = `SUBJECT: ${complaint.subject}\n\nTO: ${provider?.supportEmail || "Support"}\n\n${complaint.body}`;
    navigator.clipboard.writeText(fullText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  // Open in Default Email Client (mailto:)
  const handleOpenEmail = () => {
    const to = encodeURIComponent(provider?.supportEmail || "");
    const subject = encodeURIComponent(complaint.subject);
    const body = encodeURIComponent(complaint.body);
    const mailtoUrl = `mailto:${to}?subject=${subject}&body=${body}`;
    window.location.href = mailtoUrl;
  };

  // Download PDF
  const handleDownloadPDF = () => {
    setIsExportingPDF(true);
    try {
      generateDisputePDF({ dispute, complaint, provider });
    } catch (err) {
      console.error("PDF generation failed", err);
    } finally {
      setTimeout(() => setIsExportingPDF(false), 1000);
    }
  };

  return (
    <div className="space-y-6">
      {/* Step Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <div className="inline-flex items-center space-x-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 mb-2">
            <span>Step 4 of 4</span>
            <span>•</span>
            <span>Ready-to-Send Complaint</span>
          </div>
          <h2 className="text-xl sm:text-2xl font-bold text-white">
            Review & Dispatch Your Formal Complaint
          </h2>
          <p className="text-sm text-slate-400 mt-1">
            Generated by Claude with verified support routing, transaction table, and statutory SLA citations.
          </p>
        </div>

        {/* Tone Selector */}
        <div className="flex items-center bg-slate-900 p-1 rounded-xl border border-slate-800">
          <span className="text-xs text-slate-400 px-2 font-medium">Tone:</span>
          <button
            type="button"
            onClick={() => setTone('polite')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              tone === 'polite'
                ? 'bg-teal-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            🕊️ Polite
          </button>
          <button
            type="button"
            onClick={() => setTone('firm')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              tone === 'firm'
                ? 'bg-emerald-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            ⚖️ Firm
          </button>
          <button
            type="button"
            onClick={() => setTone('final_notice')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              tone === 'final_notice'
                ? 'bg-rose-600 text-white shadow-sm'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            🚨 Final Notice
          </button>
        </div>
      </div>

      {/* Provider & Regulatory SLA Bar */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 sm:p-5 grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="flex items-start space-x-3">
          <div className="p-2.5 rounded-xl bg-slate-800 text-emerald-400 flex-shrink-0">
            <Building className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider block">
              Official Routing Email
            </span>
            <span className="text-sm font-bold text-white block mt-0.5">
              {provider?.supportEmail || "Support Department"}
            </span>
            <span className="text-xs text-slate-400">
              {provider?.name || primaryTx.provider}
            </span>
          </div>
        </div>

        <div className="flex items-start space-x-3">
          <div className="p-2.5 rounded-xl bg-slate-800 text-cyan-400 flex-shrink-0">
            <Clock className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider block">
              Statutory SLA Window
            </span>
            <span className="text-sm font-bold text-cyan-400 block mt-0.5">
              {provider?.slaLabel || "48 Hours"}
            </span>
            <span className="text-xs text-slate-400">
              {regulator?.shortName} Guidelines
            </span>
          </div>
        </div>

        <div className="flex items-start space-x-3">
          <div className="p-2.5 rounded-xl bg-slate-800 text-amber-400 flex-shrink-0">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider block">
              Escalation Authority (CC)
            </span>
            <span className="text-sm font-bold text-white block mt-0.5">
              {regulator?.email}
            </span>
            <span className="text-xs text-slate-400">
              {regulator?.shortName}
            </span>
          </div>
        </div>
      </div>

      {/* Editable Complaint Subject & Body */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl">
        {/* Subject Bar */}
        <div className="px-5 py-3.5 bg-slate-950 border-b border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div className="flex items-center space-x-2 w-full">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider flex-shrink-0">
              Subject:
            </span>
            <input
              type="text"
              value={complaint.subject}
              onChange={(e) => setComplaint({ ...complaint, subject: e.target.value })}
              className="w-full bg-transparent text-sm font-bold text-white focus:outline-none focus:ring-1 focus:ring-emerald-500 rounded px-1.5 py-0.5 font-mono"
            />
          </div>
        </div>

        {/* Body Area */}
        <div className="p-5">
          <textarea
            rows={14}
            value={complaint.body}
            onChange={(e) => setComplaint({ ...complaint, body: e.target.value })}
            className="w-full bg-slate-950 border border-slate-800/80 rounded-xl p-4 text-xs sm:text-sm text-slate-200 font-mono leading-relaxed focus:outline-none focus:ring-2 focus:ring-emerald-500/50 resize-y"
          />
        </div>

        {/* Actions Bar */}
        <div className="px-5 py-4 bg-slate-950/80 border-t border-slate-800 flex flex-wrap items-center justify-between gap-3">
          <div className="flex flex-wrap items-center gap-2">
            {/* Copy Button */}
            <button
              type="button"
              onClick={handleCopy}
              className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-white transition-colors flex items-center space-x-1.5 shadow"
            >
              {copied ? (
                <>
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  <span className="text-emerald-400">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 text-slate-400" />
                  <span>Copy Text</span>
                </>
              )}
            </button>

            {/* Open in Email App */}
            <button
              type="button"
              onClick={handleOpenEmail}
              className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-white transition-colors flex items-center space-x-1.5 shadow"
            >
              <Mail className="w-4 h-4 text-cyan-400" />
              <span>Open in Email App</span>
            </button>

            {/* Download PDF */}
            <button
              type="button"
              onClick={handleDownloadPDF}
              disabled={isExportingPDF}
              className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-white transition-colors flex items-center space-x-1.5 shadow"
            >
              <Download className="w-4 h-4 text-amber-400" />
              <span>{isExportingPDF ? "Generating PDF..." : "Download Official PDF"}</span>
            </button>
          </div>

          {/* Mark as Sent (Transitions to Tracker) */}
          <button
            type="button"
            onClick={onMarkAsSent}
            className="w-full sm:w-auto px-5 py-2.5 rounded-xl text-xs sm:text-sm font-bold bg-emerald-500 hover:bg-emerald-400 text-slate-950 transition-all shadow-lg shadow-emerald-500/20 flex items-center justify-center space-x-2"
          >
            <Send className="w-4 h-4" />
            <span>Mark as Sent & Start Tracker</span>
          </button>
        </div>
      </div>

      {/* Back button */}
      <div className="pt-2">
        <button
          type="button"
          onClick={onBack}
          className="px-4 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors flex items-center space-x-1.5"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Edit Issue / Details</span>
        </button>
      </div>
    </div>
  );
}
